# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).


from __future__ import print_function, division


__all__ = ['say_hello']

# Cell
#export
#nbdev_comment from __future__ import print_function, division

import random

def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

